spring:
  h2.console.enabled: on
  jpa:
    show-sql: on
    properties.hibernate:
     format_sql: true
     use_sql_comments: true
  data.rest.base-path: /api

logging.level.org.hibernate.type: trace

server.port: 8080
